### PR TITLE
change to the additions overlay function call

### PR DESCRIPTION
**Pull request by LateNightIceCream**
regarding  #54

### CODE REVIEW

**Comment by Misterio77** [comment]
Thank you!

**Comment by arthsmn** [comment]
When using this change and trying to rebuild my system I get an infinite recursion error.

**Comment by Edgaras1** [comment]
> When using this change and trying to rebuild my system I get an infinite recursion error.

Check your pkgs/default https://github.com/Misterio77/nix-starter-configs/blob/main/standard/pkgs/default.nix

**Comment by Edgaras1** [comment]
> When using this change and trying to rebuild my system I get an infinite recursion error.

Change your pkgs default.nix https://github.com/Misterio77/nix-starter-configs/blob/main/standard/pkgs/default.nix

from { pkgs , ... }: { }  to pkgs: {}

**Comment by arthsmn** [comment]
> > When using this change and trying to rebuild my system I get an infinite recursion error.
> 
> Change your pkgs default.nix https://github.com/Misterio77/nix-starter-configs/blob/main/standard/pkgs/default.nix
> 
> from { pkgs , ... }: { } to pkgs: {}

Sorry, forgot to do this!

**Pull request merged**
